# Generated by Django 6.0 on 2026-02-11 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_owner_name', models.CharField(max_length=255)),
                ('sub_address', models.TextField()),
                ('sub_pan', models.CharField(max_length=50)),
                ('sub_mobile_no', models.CharField(max_length=20)),
                ('sub_email_address', models.EmailField(max_length=254)),
                ('sub_is_active', models.BooleanField(default=False)),
                ('sub_starting_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_ending_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
